const rawCityData = [
    ["antwerp", "belgium"],
    ["athens", "greece"],
    ["basseterre", "saint kitts and nevis"],
    ["bergen", "norway"],
    ["berlin", "germany"],
    ["boston", "usa"],
    ["brussels", "belgium"],
    ["budapest", "hungary"],
    ["calico", "usa"],
    ["cartagena", "colombia"],
    ["colon", "panama"],
    ["copenhagen", "denmark"],
    ["corfu town", "greece"],
    ["fort-de-france", "martinique"],
    ["gdansk", "poland"],
    ["genova", "italy"],
    ["george town", "cayman islands"],
    ["hamburg", "germany"],
    ["helsinki", "finland"],
    ["kotor", "montenegro"],
    ["las vegas", "usa"],
    ["london", "england"],
    ["los angeles", "usa"],
    ["luxembourg", "luxembourg"],
    ["lyon", "france"],
    ["malmo", "sweden"],
    ["milan", "italy"],
    ["monte-carlo", "monaco"],
    ["new york", "usa"],
    ["oslo", "norway"],
    ["panama city", "panama"],
    ["paris", "france"],
    ["porto", "portugal"],
    ["prague", "czechia"],
    ["rome", "italy"],
    ["rotterdam", "netherlands"],
    ["rovaniemi", "finland"],
    ["saint john's", "antigua and barbuda"],
    ["saint petersburg", "russia"],
    ["san francisco", "usa"],
    ["san marino city", "san marino"],
    ["santo domingo", "dominican republic"],
    ["stockholm", "sweden"],
    ["strasbourg", "france"],
    ["tallinn", "estonia"],
    ["the hague", "netherlands"],
    ["valletta", "malta"]
];
